In [1]:
import pandas as pd
import sqlite3
pd.set_option('display.max_columns', 999)
pd.set_option('display.max_rows', 999)

In [2]:
merged = pd.read_csv('medicines.csv')

In [4]:
merged = merged.rename(columns={'Therapeutic Class': 'therapeutic_class'})

In [8]:
conn = sqlite3.connect('medicines.db')
merged.to_sql('medicines', conn, if_exists='replace', index=False)
conn.close()

##### Ideas - To do!

- generic preprocess of all columns/standardization
- database search for the alternative medicines / similarity search based on some features
- front - end / UI
- categorisation of medicines into Therapeutic Class

In [2]:
df = pd.read_csv('medicine_dataset.csv')
df.shape

C:\Users\Asus\AppData\Local\Temp\ipykernel_31836\1595060483.py:1: DtypeWarning: Columns (42,43,44,45,46,47,48) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv('medicine_dataset.csv')

(248218, 58)

In [3]:
df_2 = pd.read_csv('A_Z_medicines_dataset_of_India.csv')
df_2.shape

(253973, 9)

In [4]:
#generic preprocessing
def process_text(text):
    # Handle NaN/float values by converting to string
    if pd.isna(text):
        return ''
    # Convert to string and process
    text = str(text)
    text = text.lower()
    text = text.replace(' ', '_')
    text = text.replace('-', '_')
    text = text.replace('/', '_')
    text = text.replace('(', '')
    text = text.replace(')', '')
    return text

columns_to_process = ['name', 'substitute0', 'substitute1', 'substitute2',
       'substitute3', 'substitute4', 'sideEffect0', 'sideEffect1',
       'sideEffect2', 'sideEffect3', 'sideEffect4', 'sideEffect5',
       'sideEffect6', 'sideEffect7', 'sideEffect8', 'sideEffect9',
       'sideEffect10', 'sideEffect11', 'sideEffect12', 'sideEffect13',
       'sideEffect14', 'sideEffect15', 'sideEffect16', 'sideEffect17',
       'sideEffect18', 'sideEffect19', 'sideEffect20', 'sideEffect21',
       'sideEffect22', 'sideEffect23', 'sideEffect24', 'sideEffect25',
       'sideEffect26', 'sideEffect27', 'sideEffect28', 'sideEffect29',
       'sideEffect30', 'sideEffect31', 'sideEffect32', 'sideEffect33',
       'sideEffect34', 'sideEffect35', 'sideEffect36', 'sideEffect37',
       'sideEffect38', 'sideEffect39', 'sideEffect40', 'sideEffect41', 'use0',
       'use1', 'use2', 'use3', 'use4', 'Chemical Class', 'Habit Forming',
       'Therapeutic Class', 'Action Class']

df = df.fillna('missing')
for column in columns_to_process:
    df[column] = df[column].apply(process_text)
df = df.drop(columns=['id'])

df_2 = df_2.rename(columns={'price(₹)' : 'price'})
df_2 = df_2.drop(columns=['id'])
columns_to_process = ['name', 'price', 'Is_discontinued', 'manufacturer_name',
       'type', 'pack_size_label', 'short_composition1', 'short_composition2']
df_2 = df_2.fillna('missing')
for column in columns_to_process:
    df_2[column] = df_2[column].apply(process_text) 

merged=df.merge(df_2, on=['name'])
merged = merged.drop_duplicates(subset='name')
merged.shape

(221306, 64)

In [5]:
merged['Action Class'].value_counts()

Action Class
missing                                                                            98458
cephalosporins:_3_generation                                                       10791
quinolones__fluroquinolones                                                         6939
fungal_ergosterol_synthesis_inhibitor                                               5891
proton_pump_inhibitors                                                              5695
macrolides                                                                          4993
glucocorticoids                                                                     4723
h1_antihistaminics_second_generation                                                3664
hmg_coa_inhibitors_statins                                                          2534
cephalosporins:_2nd_generation                                                      2437
benzodiazepines                                                                     2434
nsaid's__non_selective_cox_1&2_inhibitors_acetic_acid                               2409
atypical_antipsychotics                                                             2357
serotonin_antagonists_5_ht3_antagonists                                             2352
aminoglycosides                                                                     1929
selective_seretonin_reuptake_inhibitors_ssris                                       1821
angiotensin_receptor_blockersarb                                                    1736
sodium_channel_modulators_aed                                                       1590
analgesic_&_antipyretic_pcm                                                         1545
cell_wall_active_agent__extended_spectrum_penicillin                                1524
vitamins                                                                            1324
anabolic_steroid                                                                    1278
natural_progesterone                                                                1249
nsaid's__selective_cox_2_inhibitors                                                 1207
beta_blocker__cardioselective                                                       1184
calcium_channel_blockers__dihydropyridines_dhp                                      1144
cephalosporins:_1st_generation                                                      1051
cell_wall_active_agent__carbapenems                                                 1004
antiprotozoal_agents                                                                 958
nootropic_agent                                                                      931
histamine_analog__meniere's_disease                                                  930
sulfonylureas_insulin_secretogogues                                                  889
hepatoprotectives                                                                    836
h1_antihistaminics_first_generation                                                  831
nsaid's_non_selective_cox_1&2_inhibitors_others                                      823
antimalarial__artemisinin_and_derivatives                                            818
tricyclic_antidepressants                                                            769
synaptic_vescicle_2_a_protein_ligand_aed                                             681
alpha_glucosidase_inhibitors                                                         678
biguanides                                                                           674
xanthine_oxidase_inhibitors_gout                                                     655
dpp_4_inhibitors                                                                     642
theophylline_&_its_derivatives                                                       608
ectoparasiticides                                                                    598
progestins_first_generation                                                          595
serotonin_norepinephrine_reuptake_inhibitors_snris                                   582
alpha_2_delta_ligands_aed                                                            573
proteolytic_enzymes                                                                  569
angiotensin_converting_enzyme_ace_inhibitors                                         567
phosphodiesterase_v_inhibitors                                                       564
oxazolidinone                                                                        525
typical_antipsychotics                                                               520
cell_membrane_active_agent                                                           487
retinoids__first_generation                                                          480
nsaid's__non_selective_cox_1&2_inhibitors_enolic_acids                               477
lincosamides                                                                         462
antiviral_non_hiv_drugs                                                              449
opioids                                                                              438
skeletal_muscle_relaxant__centrally_acting                                           436
tetracyclines                                                                        422
tear_substitues                                                                      421
dopamine_d2_receptor_antagonist_prokinetic_agent                                     415
haemopoetic_agents                                                                   375
immunosuppressant__calcineurin_inhibitors                                            364
tyrosine_kinase_inhibitors                                                           353
h2_receptor_blocker                                                                  352
potassium_channel_opener                                                             351
gonadotropins                                                                        348
no_donors                                                                            344
antiseptics_and_disinfectants                                                        319
amino_acids                                                                          313
p2y12_inhibitors_adp_receptor                                                        304
uroselective_adrenergic_receptorα1a_antagonist                                       303
osmotic_laxatives_purgative                                                          298
antimetabolites                                                                      294
uricosuric_agent_gout                                                                280
rna_polymerase_inhibitors__rifamycins                                                279
phosphodiesterase_iv_inhibitors_smooth_muscle_relaxant                               273
sympthatomimmetics__alpha_1_nasal                                                    273
sglt2_inhibitors                                                                     272
haemostatic_agent                                                                    270
beta_blocker__non_selective                                                          268
calcium_channel_blocker__migraine_prevention                                         261
alpha_&_beta_blocker                                                                 261
beta_2_agonist___uterus                                                              260
high_ceiling_diuretics_inhibitors_of_na+_k+__2cl_cotransport                         257
antifibrinolytic                                                                     257
alkaloids_cytotoxic_agents                                                           247
antimicrotubule_agents__taxanes                                                      237
non_benzodiazepine_hypnotics_z_compounds                                             233
low_molecular_weight_heparin_lmwh                                                    231
erythropoiesis_stimulating_agent_esa                                                 231
aromatase_inhibitor                                                                  223
alkylating_agent                                                                     223
disease_modifying_anti_rheumatoid_drugs_dmards__non_biologics                        211
5_nitroimidazole_antiprotozoal_&_antibacterial                                       206
platinum_compounds_anticancer                                                        201
antimalarial__others                                                                 197
antifungal_others                                                                    188
stimulant_laxatives_purgative                                                        188
immunosuppressant__purine_analogs                                                    187
noradrenergic_and_specific_serotonergic_antidepressants_nassas                       187
glycopeptides                                                                        185
anti_ulcerants                                                                       180
chloramphenicol                                                                      180
cephalosporins:_4th_generation                                                       179
leukotriene_antagonists                                                              178
serotonin_5_ht4_receptor_agonist_prokinetic_agent                                    176
thiazolidinedioneppar_gamma_agonist                                                  173
antimetabolite__methotrexate                                                         169
nsaid's__non_selective_cox_1&2_inhibitors_topical                                    169
proteoglycan_synthesis_stimulator                                                    167
antimalarial__aminoquinolines                                                        167
thyroid_hormones                                                                     167
calcium_channel_antagonist__antihistamine                                            166
nsaid's__non_selective_cox_1&2_inhibitors_propionic_acid                             165
oral_factor_xa_inhibitors                                                            164
calcium_channel_blockers__nondihydropyridines                                        161
partial_estrogen_agonist                                                             160
crystalloids                                                                         157
osteoarthritis__hyaluronic_acid                                                      148
local_anaesthetic_amides                                                             145
anticholinergic__centrally_acting                                                    142
bone_resorption_inhibitor__bisphosphonates                                           140
urinary_antiseptic_nitrofurantoin                                                    136
stomatologicals__antimicrobials                                                      135
5_alpha__reductase_inhibitor_5ari                                                    134
penem                                                                                133
low_ceiling_diuretics_inhibitors_of_na+cl_symport                                    132
lipase_inhibitor                                                                     129
μ_opioid_receptor_&_norepinephrine_reuptake_inhibitor_nri                            129
acetylcysteine__mucolytic                                                            127
anticancer_others                                                                    126
phosphorous_binder                                                                   123
anticholinergics                                                                     123
antacids                                                                             119
nucleoside_nucleotide_reverse_transcriptase_inhibitors_nrtis_                        118
cholinesterase_inhibitors___alzheimer's_disease                                      116
short_acting_β2_agonists                                                             116
protein_synthesis_inhibitors                                                         113
estrogens                                                                            110
mood_stabilizers                                                                     110
direct_antispasmodic_bladder                                                         109
nsaid's__non_selective_cox_1&2_inhibitors_fenamates                                  105
mycobacterial_cell_wall_inhibitors_ethambutol                                        104
uterotonic_and_abortificient                                                         101
psoralen_&_derivatives                                                                95
skeletal_muscle_relaxant__peripherally_acting                                         94
dopamine_agonists                                                                     94
keratoplastic_and_keratolytic_agents                                                  93
androgens                                                                             93
i_f_sodium_channel_sinoatrial_node_current_blockers                                   91
inhalational_corticosteriods                                                          90
adrenergic_receptor_alpha_antagonist__selective                                       90
5__aminosalicylic_acid_5_asa                                                          90
pg_f2_alpha_analogue                                                                  89
enkephalinase_inhibitor                                                               85
gnrh_agonists_analogue                                                                84
opioid_agonist__antidiarrheal                                                         82
thalidomide_&_its_immunomodulatory_derivatives_imids                                  80
fungal_cell_wall_synthesis_inhibitor_echiocandins                                     79
ppar_alpha_agonists_fibrate                                                           77
dopamine_d2_receptor_antagonist__prochlorperazine                                     77
fungal_cell_membrane_active_agent                                                     76
unfractionated_heparin_ufh                                                            76
fatty_acid_modulator_&_sodium_channel_blocker                                         75
dopamine_agonists_hyperprolactinemia                                                  74
ampicillin_&_sulbactam_ester_compound                                                 71
general_anaesthetic_agents                                                            71
direct_thrombin_inhibitor__oral                                                       70
minerals                                                                              70
triptans_5ht_1b_1d_agonist                                                            68
mucolytics                                                                            68
selective_m3_anticholinergic_bladder                                                  68
mycobacterial_fatty_acid_synthase                                                     68
late_sodium_channel_blocker__angina                                                   67
cough_suppressants                                                                    66
digestive_enzymes                                                                     66
barbiturate                                                                           66
meglitinides_insulin_secretogogues                                                    63
killed_vaccine                                                                        63
somatostatin_analogues                                                                62
immunoglobulin                                                                        61
antioxidant                                                                           61
vitamin_k_antagonists                                                                 61
topical_glucocorticoids                                                               61
monobactams                                                                           61
selective_neuronal_potassium_channel_openers_snepco                                   61
carbonic_anhydrase_inhibitor                                                          60
capillary_permeability_reducer                                                        59
alcohol_deaddiction                                                                   59
progestins__others                                                                    59
granulocyte_colony_stimulating_factor_g_csf                                           59
beta_blocker_topical                                                                  57
anti_progesterone                                                                     57
subunit_purified_antigen                                                              56
sympathomimetics_agonist_inotropes                                                    56
anticholinergic__mydriatic_and_cycloplegic                                            54
vasopressin_analogues                                                                 54
prostaglandin_e1_pge1_analogue_obstetrics                                             53
non_selective_anticholinergic_bladder                                                 52
melatonin_agonist                                                                     52
androgen_receptor_antagonist                                                          51
progestins_third_generation                                                           51
anti_pigmentation_&_skin_lightening_agent                                             51
proteasome_inhibitor                                                                  50
probiotics                                                                            49
stimulant__drug_for_excessive_sleepiness                                              49
first_generation_thrombolytics                                                        47
potassium__sparing_diuretics                                                          47
immunosuppressant__mtor_inhibitors                                                    46
retinoids__third_generation                                                           46
anti_spasmodics_ibd                                                                   45
androgen__endometereosis                                                              44
cell_wall_synthesis_inhibitor__uti                                                    44
class_iii_agents__anti_arrhythmic                                                     44
cell_wall_active_agent___narrow_spectrum_penicillin                                   44
colloids_plasma_substitutes                                                           43
selective_beta_3_adrenoceptor_agonist_bladder                                         43
phosphodiesterase_iii_inhibiotrs_pvd                                                  42
glycoprotein_iib_iiia_inhibitors                                                      42
janus_kinase_inhibitors                                                               42
sympthatomimmetics_adhd_non_stimulant                                                 42
cd_20_inhibitor                                                                       41

In [6]:
merged['Therapeutic Class'].value_counts()

Therapeutic Class
anti_infectives                49899
gastro_intestinal              30204
pain_analgesics                28758
neuro_cns                      21315
respiratory                    20978
cardiac                        16578
anti_diabetic                  10372
ophthal                         9382
derma                           8756
hormones                        4806
gynaecological                  4055
vitamins_minerals_nutrients     3785
anti_neoplastics                3183
blood_related                   2441
urology                         1705
ophthal_otologicals             1530
anti_malarials                  1446
sex_stimulants_rejuvenators      682
others                           459
otologicals                      446
vaccines                         301
stomatologicals                  162
missing                           63
Name: count, dtype: int64

In [7]:
merged.Is_discontinued.value_counts()

Is_discontinued
false    214267
true       7039
Name: count, dtype: int64

Which medicines have the rarest side effects?

In [8]:
merged[merged['sideEffect41']!='missing']

,name,substitute0,substitute1,substitute2,substitute3,substitute4,sideEffect0,sideEffect1,sideEffect2,sideEffect3,sideEffect4,sideEffect5,sideEffect6,sideEffect7,sideEffect8,sideEffect9,sideEffect10,sideEffect11,sideEffect12,sideEffect13,sideEffect14,sideEffect15,sideEffect16,sideEffect17,sideEffect18,sideEffect19,sideEffect20,sideEffect21,sideEffect22,sideEffect23,sideEffect24,sideEffect25,sideEffect26,sideEffect27,sideEffect28,sideEffect29,sideEffect30,sideEffect31,sideEffect32,sideEffect33,sideEffect34,sideEffect35,sideEffect36,sideEffect37,sideEffect38,sideEffect39,sideEffect40,sideEffect41,use0,use1,use2,use3,use4,Chemical Class,Habit Forming,Therapeutic Class,Action Class,price,Is_discontinued,manufacturer_name,type,pack_size_label,short_composition1,short_composition2
32132,balila_capsule,missing,missing,missing,missing,missing,sodium_retention,nausea,vomiting,abdominal_pain,diarrhea,hypertrichosis_lanuginosa,decreased_appetite,increased_uric_acid_level_in_blood,extrapyramidal_symptoms,decreased_white_blood_cell_count_lymphocytes,low_blood_platelets,decreased_hemoglobin,increased_white_blood_cell_count_eosinophils,bleeding,hypersensitivity,decreased_immunoglobulins_in_infants,excessive_hair_growth_on_face,unusual_production_of_breast_milk_in_women_and...,pancreatic_inflammation,increased_androgen_levels,decreased_libido,headache,dizziness,blurred_vision,cataract,ring_scotoma,double_vision,lacrimation_flow_of_tears,hypotension_low_blood_pressure,enlarged_heart,cardiac_failure,arrhythmia_irregular_heartbeats,breathlessness,pulmonary_hypertension_high_blood_pressure,increased_aspartate_aminotransferase,increased_alkaline_phosphatase_level_in_blood,"musculoskeletal_bone,_muscle_or_joint_pain",azotemia_increased_nitrogen_containing_compoun...,decreased_creatinine_clearance,nephritic_syndrome,voice_change,abnormal_faces_in_children,managing_hypoglycemia_low_blood_sugar,missing,missing,missing,missing,thiadiazines_derivative,no,anti_diabetic,missing,2016.0,false,jolly_healthcare,allopathy,strip_of_15_capsules,diazoxide_25mg,missing
32310,balila_25mg_capsule,missing,missing,missing,missing,missing,sodium_retention,nausea,vomiting,abdominal_pain,diarrhea,hypertrichosis_lanuginosa,decreased_appetite,increased_uric_acid_level_in_blood,extrapyramidal_symptoms,decreased_white_blood_cell_count_lymphocytes,low_blood_platelets,decreased_hemoglobin,increased_white_blood_cell_count_eosinophils,bleeding,hypersensitivity,decreased_immunoglobulins_in_infants,excessive_hair_growth_on_face,unusual_production_of_breast_milk_in_women_and...,pancreatic_inflammation,increased_androgen_levels,decreased_libido,headache,dizziness,blurred_vision,cataract,ring_scotoma,double_vision,lacrimation_flow_of_tears,hypotension_low_blood_pressure,enlarged_heart,cardiac_failure,arrhythmia_irregular_heartbeats,breathlessness,pulmonary_hypertension_high_blood_pressure,increased_aspartate_aminotransferase,increased_alkaline_phosphatase_level_in_blood,"musculoskeletal_bone,_muscle_or_joint_pain",azotemia_increased_nitrogen_containing_compoun...,decreased_creatinine_clearance,nephritic_syndrome,voice_change,abnormal_faces_in_children,managing_hypoglycemia_low_blood_sugar,missing,missing,missing,missing,thiadiazines_derivative,no,anti_diabetic,missing,1478.0,false,jolly_healthcare,allopathy,strip_of_10_capsules,diazoxide_25mg,missing

We can see that only two of the medicines contain this side effect. They are composed of 'diazoxide_25mg'. Lets see if there are other medicines that have this composition and if they have many side effects

In [9]:
merged[merged['short_composition1']=='diazoxide_25mg']

,name,substitute0,substitute1,substitute2,substitute3,substitute4,sideEffect0,sideEffect1,sideEffect2,sideEffect3,sideEffect4,sideEffect5,sideEffect6,sideEffect7,sideEffect8,sideEffect9,sideEffect10,sideEffect11,sideEffect12,sideEffect13,sideEffect14,sideEffect15,sideEffect16,sideEffect17,sideEffect18,sideEffect19,sideEffect20,sideEffect21,sideEffect22,sideEffect23,sideEffect24,sideEffect25,sideEffect26,sideEffect27,sideEffect28,sideEffect29,sideEffect30,sideEffect31,sideEffect32,sideEffect33,sideEffect34,sideEffect35,sideEffect36,sideEffect37,sideEffect38,sideEffect39,sideEffect40,sideEffect41,use0,use1,use2,use3,use4,Chemical Class,Habit Forming,Therapeutic Class,Action Class,price,Is_discontinued,manufacturer_name,type,pack_size_label,short_composition1,short_composition2
32132,balila_capsule,missing,missing,missing,missing,missing,sodium_retention,nausea,vomiting,abdominal_pain,diarrhea,hypertrichosis_lanuginosa,decreased_appetite,increased_uric_acid_level_in_blood,extrapyramidal_symptoms,decreased_white_blood_cell_count_lymphocytes,low_blood_platelets,decreased_hemoglobin,increased_white_blood_cell_count_eosinophils,bleeding,hypersensitivity,decreased_immunoglobulins_in_infants,excessive_hair_growth_on_face,unusual_production_of_breast_milk_in_women_and...,pancreatic_inflammation,increased_androgen_levels,decreased_libido,headache,dizziness,blurred_vision,cataract,ring_scotoma,double_vision,lacrimation_flow_of_tears,hypotension_low_blood_pressure,enlarged_heart,cardiac_failure,arrhythmia_irregular_heartbeats,breathlessness,pulmonary_hypertension_high_blood_pressure,increased_aspartate_aminotransferase,increased_alkaline_phosphatase_level_in_blood,"musculoskeletal_bone,_muscle_or_joint_pain",azotemia_increased_nitrogen_containing_compoun...,decreased_creatinine_clearance,nephritic_syndrome,voice_change,abnormal_faces_in_children,managing_hypoglycemia_low_blood_sugar,missing,missing,missing,missing,thiadiazines_derivative,no,anti_diabetic,missing,2016.0,false,jolly_healthcare,allopathy,strip_of_15_capsules,diazoxide_25mg,missing
32310,balila_25mg_capsule,missing,missing,missing,missing,missing,sodium_retention,nausea,vomiting,abdominal_pain,diarrhea,hypertrichosis_lanuginosa,decreased_appetite,increased_uric_acid_level_in_blood,extrapyramidal_symptoms,decreased_white_blood_cell_count_lymphocytes,low_blood_platelets,decreased_hemoglobin,increased_white_blood_cell_count_eosinophils,bleeding,hypersensitivity,decreased_immunoglobulins_in_infants,excessive_hair_growth_on_face,unusual_production_of_breast_milk_in_women_and...,pancreatic_inflammation,increased_androgen_levels,decreased_libido,headache,dizziness,blurred_vision,cataract,ring_scotoma,double_vision,lacrimation_flow_of_tears,hypotension_low_blood_pressure,enlarged_heart,cardiac_failure,arrhythmia_irregular_heartbeats,breathlessness,pulmonary_hypertension_high_blood_pressure,increased_aspartate_aminotransferase,increased_alkaline_phosphatase_level_in_blood,"musculoskeletal_bone,_muscle_or_joint_pain",azotemia_increased_nitrogen_containing_compoun...,decreased_creatinine_clearance,nephritic_syndrome,voice_change,abnormal_faces_in_children,managing_hypoglycemia_low_blood_sugar,missing,missing,missing,missing,thiadiazines_derivative,no,anti_diabetic,missing,1478.0,false,jolly_healthcare,allopathy,strip_of_10_capsules,diazoxide_25mg,missing

The rarest side effects are in balila capsule and balila 24mg capsule.
The medicine has all side effects and is in the anti diabetic class. 

Lets check the other anti diabetic medicines to see if they frequently have a lot of side effects

In [10]:
merged[merged['Therapeutic Class']=='anti_diabetic']

,name,substitute0,substitute1,substitute2,substitute3,substitute4,sideEffect0,sideEffect1,sideEffect2,sideEffect3,sideEffect4,sideEffect5,sideEffect6,sideEffect7,sideEffect8,sideEffect9,sideEffect10,sideEffect11,sideEffect12,sideEffect13,sideEffect14,sideEffect15,sideEffect16,sideEffect17,sideEffect18,sideEffect19,sideEffect20,sideEffect21,sideEffect22,sideEffect23,sideEffect24,sideEffect25,sideEffect26,sideEffect27,sideEffect28,sideEffect29,sideEffect30,sideEffect31,sideEffect32,sideEffect33,sideEffect34,sideEffect35,sideEffect36,sideEffect37,sideEffect38,sideEffect39,sideEffect40,sideEffect41,use0,use1,use2,use3,use4,Chemical Class,Habit Forming,Therapeutic Class,Action Class,price,Is_discontinued,manufacturer_name,type,pack_size_label,short_composition1,short_composition2
144,ajaduo_25mg_5mg_tablet,glyxambi_25mg_5mg_tablet,tiptengio_25mg_5mg_tablet,xilingio_25mg_5mg_tablet,missing,missing,hypoglycemia_low_blood_glucose_level,cough,nasopharyngitis_inflammation_of_the_throat_and...,urinary_tract_infection,nausea,vomiting,constipation,genital_fungal_infection,missing,missing,missing,missing,missing,missing,missing,missing,missing,missing,missing,missing,missing,missing,missing,missing,missing,missing,missing,missing,missing,missing,missing,missing,missing,missing,missing,missing,missing,missing,missing,missing,missing,missing,treatment_of_type_2_diabetes_mellitus,missing,missing,missing,missing,missing,no,anti_diabetic,missing,820.0,false,lupin_ltd,allopathy,strip_of_10_tablets,empagliflozin_25mg_,_linagliptin_5mg
157,amaryl_m__1mg_tablet_pr,glyzee_m1_pr_tablet,glimestar_m_1_tablet_pr,metride_1_tablet_pr,diapride_m1_tablet_pr,glycomet_gp_1_tablet_pr,hypoglycemia_low_blood_glucose_level,headache,nausea,diarrhea,flatulence,missing,missing,missing,missing,missing,missing,missing,missing,missing,missing,missing,missing,missing,missing,missing,missing,missing,missing,missing,missing,missing,missing,missing,missing,missing,missing,missing,missing,missing,missing,missing,missing,missing,missing,missing,missing,missing,treatment_of_type_2_diabetes_mellitus,missing,missing,missing,missing,missing,no,anti_diabetic,missing,242.84,false,sanofi_india__ltd,allopathy,strip_of_20_tablet_pr,glimepiride_1mg_,_metformin_500mg
169,amaryl_m__2mg_tablet_pr,glimiprex_mf_2_500_tablet_pr,glimestar_m_2_tablet_pr,metride_2_tablet_pr,geminor_m_2_tablet_pr,exermet_gm_502_tablet_pr,hypoglycemia_low_blood_glucose_level,headache,nausea,diarrhea,flatulence,missing,missing,missing,missing,missing,missing,missing,missing,missing,missing,missing,missing,missing,missing,missing,missing,missing,missing,missing,missing,missing,missing,missing,missing,missing,missing,missing,missing,missing,missing,missing,missing,missing,missing,missing,missing,missing,treatment_of_type_2_diabetes_mellitus,missing,missing,missing,missing,missing,no,anti_diabetic,missing,363.34,false,sanofi_india__ltd,allopathy,strip_of_20_tablet_pr,glimepiride_2mg_,_metformin_500mg
206,actrapid_hm_100iu_ml_penfill,wosulin_r_dispopen,lupisulin_r_100iu_ml_cartridge,insuman_rapid_100iu_ml_solution_for_injection,actrapid_100iu_ml_solution_for_injection,huminsulin_r_100iu_cartridge,hypoglycemia_low_blood_glucose_level,weight_gain,edema_swelling,"injection_site_reactions_pain,_swelling,_redness",missing,missing,missing,missing,missing,missing,missing,missing,missing,missing,missing,missing,missing,missing,missing,missing,missing,missing,missing,missing,missing,missing,missing,missing,missing,missing,missing,missing,missing,missing,missing,missing,missing,missing,missing,missing,missing,missing,_diabetes,missing,missing,missing,missing,insulin_analogue,no,anti_diabetic,human_insulin___short_acting,350.9,false,novo_nordisk_india_pvt_ltd,allopathy,penfill_of_3_ml_solution_for_injection,human_insulin_100iu,missing
228,apidra_100iu_cartridge,apidra_100iu_ml_solution_for_injection,missing,missing,missing,missing,hypoglycemia_low_blood_glucose_level,nasopharyngitis_inflammation_of_the_throat_and...,upper_respiratory_tract_infection,missing,missing,missing,missing,missing,missing,missing,missing,missing,missing,missing,missing,missing,missing,missing,missing,missing,missing,missing,missing,missing,missing,missing,missing,missing,missing,missing,missing,missing,missing,missing,missing,missing,missing,missing,missing,missing,missing,missing,_diabetes,missing,missing,missing,missing,insulin_analogue,no,anti_diabetic,insulin_analogues__rapid_acting,761.0,false,sanofi_india__ltd,allopathy,cartridge_of_3_ml_solution_for_injection,insulin_glulisine_100iu,missing
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
256231,zolib_m_forte_4mg_1000mg_tablet,jubiglim_m_forte_4mg_1000mg_tablet,hmet_g_forte_4mg_tablet,pridex_m_4mg_1000mg_tablet,insuform_g_forte_4mg_1000mg_tablet,glimiprex_mf_forte_4mg_1000mg_tablet,hypoglycemia_low_blood_glucose_level,headache,nausea,diarrhea,flatulence,missing,missing,missing,missing,missing,missing,missing,missing,missing,missing,missing,missing,missing,missing,missing,missing,missing,missing,missing,missing,missing,missing,missing,missing,missing,missing,missing,missing,missing,missing,missing,missing,missing,missing,missing,missing,missing,treatment_of_type_2_diabetes_mellitus,missing,missing,missing,missing,missing,no,anti_diabetic,missing,195.0,false,libramed_pharmaceuticals_private_ltd,allopathy,strip_of_15_tablets,glimepiride_4mg_,_metformin_1000mg
256521,zolib_m_3mg_1000mg_tablet,wonride_m_3_forte_tablet,glimiprime_m_3_forte_tablet,glimiprex_mf_forte_3mg_1000mg_tablet,hmet_g_forte_3mg_tablet,glimiset_m_forte_3mg_1000mg_tablet,hypoglycemia_low_blood_glucose_level,headache,nausea,diarrhea,flatulence,missing,missing,missing,missing,missing,missing,missing,missing,missing,missing,missing,missing,missing,missing,missing,missing,missing,missing,missing,missing,missing,missing,missing,missing,missing,missing,missing,missing,missing,missing,missing,missing,missing,missing,missing,missing,missing,treatment_of_type_2_diabetes_mellitus,missing,missing,missing,missing,missing,no,anti_diabetic,missing,180.0,false,libramed_pharmaceuticals_private_ltd,allopathy,strip_of_15_tablets,glimepiride_3mg_,_metformin_1000mg
256657,zobose_0.2mg_tablet,vozuca_activ_0.2_tablet,voglibite_0.2_tablet,vogliboz_0.2_tablet,ppg_0.2_tablet,vingose_0.2mg_flashtab,skin_rash,flatulence,abdominal_pain,diarrhea,missing,missing,missing,missing,missing,missing,missing,missing,missing,missing,missing,missing,missing,missing,missing,missing,missing,missing,missing,missing,missing,missing,missing,missing,missing,missing,missing,missing,missing,missing,missing,missing,missing,missing,missing,missing,missing,missing,treatment_of_type_2_diabetes_mellitus,missing,missing,missing,missing,valiolamine_derivative,no,anti_diabetic,alpha_glucosidase_inhibitors,66.9,false,zoic_lifesciences,allopathy,strip_of_10_tablets,voglibose_0.2mg,missing
256745,zepvog_500mg_0.3mg_tablet_sr,vogs_m_0.3_tablet_sr,voglibite_m_0.3_tablet_sr,megavog_mf_0.3_500_tablet_sr,starvog_m_0.3_tablet_sr,vozuca_m_0.3_activ_tablet_sr,flatulence,diarrhea,bloating,abdominal_pain,vomiting,decreased_appetite,missing,missing,missing,missing,missing,missing,missing,missing,missing,missing,missing,missing,missing,missing,missing,missing,missing,missing,missing,missing,missing,missing,missing,missing,missing,missing,missing,missing,missing,missing,missing,missing,missing,missing,missing,missing,treatment_of_type_2_diabetes_mellitus,missing,missing,missing,missing,missing,no,anti_diabetic,missing,79.0,false,merlion_lifescience_pvt_ltd,allopathy,strip_of_10_tablet_sr,metformin_500mg_,_voglibose_0.3mg
256933,zimpomet_500mg_tablet,biciphage_500_tablet,okamet_500_tablet,etformin_500mg_tablet,bigomet_500_tablet,forson_500mg_tablet,diarrhea,nausea,vomiting,flatulence,missing,missing,missing,missing,missing,missing,missing,missing,missing,missing,missing,missing,missing,missing,missing,missing,missing,missing,missing,missing,missing,missing,missing,missing,missing,missing,missing,missing,missing,missing,missing,missing,missing,missing,missing,missing,missing,missing,treatment_of_type_2_diabetes_mellitus,missing,missing,missing,missing,biguanides_derivative,no,anti_diabetic,biguanides,28.0,false,leenate_pharma_pvt_ltd,allopathy,strip_of_10_tablets,metformin_500mg,missing

They have a lot fewer side effects as we see. Balila capsule and balila 24mg capsule medicines are being used for 'managing_hypoglycemia_low_blood_sugar' as we can see in the 'use0' column. Lets check for other medicines that are being used for the same thing.

In [11]:
merged[merged['use0']=='managing_hypoglycemia_low_blood_sugar'].shape

(2, 64)

In [12]:
merged[merged['short_composition1']=='diazoxide_25mg'].shape, merged[merged['short_composition2']=='diazoxide_25mg'].shape

((2, 64), (0, 64))

Check chemical class

In [13]:
merged[merged['Chemical Class']=='thiadiazines_derivative'].shape

(2, 64)

How about manufacturer

In [14]:
merged[merged['manufacturer_name']=='jolly_healthcare']

,name,substitute0,substitute1,substitute2,substitute3,substitute4,sideEffect0,sideEffect1,sideEffect2,sideEffect3,sideEffect4,sideEffect5,sideEffect6,sideEffect7,sideEffect8,sideEffect9,sideEffect10,sideEffect11,sideEffect12,sideEffect13,sideEffect14,sideEffect15,sideEffect16,sideEffect17,sideEffect18,sideEffect19,sideEffect20,sideEffect21,sideEffect22,sideEffect23,sideEffect24,sideEffect25,sideEffect26,sideEffect27,sideEffect28,sideEffect29,sideEffect30,sideEffect31,sideEffect32,sideEffect33,sideEffect34,sideEffect35,sideEffect36,sideEffect37,sideEffect38,sideEffect39,sideEffect40,sideEffect41,use0,use1,use2,use3,use4,Chemical Class,Habit Forming,Therapeutic Class,Action Class,price,Is_discontinued,manufacturer_name,type,pack_size_label,short_composition1,short_composition2
32132,balila_capsule,missing,missing,missing,missing,missing,sodium_retention,nausea,vomiting,abdominal_pain,diarrhea,hypertrichosis_lanuginosa,decreased_appetite,increased_uric_acid_level_in_blood,extrapyramidal_symptoms,decreased_white_blood_cell_count_lymphocytes,low_blood_platelets,decreased_hemoglobin,increased_white_blood_cell_count_eosinophils,bleeding,hypersensitivity,decreased_immunoglobulins_in_infants,excessive_hair_growth_on_face,unusual_production_of_breast_milk_in_women_and...,pancreatic_inflammation,increased_androgen_levels,decreased_libido,headache,dizziness,blurred_vision,cataract,ring_scotoma,double_vision,lacrimation_flow_of_tears,hypotension_low_blood_pressure,enlarged_heart,cardiac_failure,arrhythmia_irregular_heartbeats,breathlessness,pulmonary_hypertension_high_blood_pressure,increased_aspartate_aminotransferase,increased_alkaline_phosphatase_level_in_blood,"musculoskeletal_bone,_muscle_or_joint_pain",azotemia_increased_nitrogen_containing_compoun...,decreased_creatinine_clearance,nephritic_syndrome,voice_change,abnormal_faces_in_children,managing_hypoglycemia_low_blood_sugar,missing,missing,missing,missing,thiadiazines_derivative,no,anti_diabetic,missing,2016.0,false,jolly_healthcare,allopathy,strip_of_15_capsules,diazoxide_25mg,missing
32310,balila_25mg_capsule,missing,missing,missing,missing,missing,sodium_retention,nausea,vomiting,abdominal_pain,diarrhea,hypertrichosis_lanuginosa,decreased_appetite,increased_uric_acid_level_in_blood,extrapyramidal_symptoms,decreased_white_blood_cell_count_lymphocytes,low_blood_platelets,decreased_hemoglobin,increased_white_blood_cell_count_eosinophils,bleeding,hypersensitivity,decreased_immunoglobulins_in_infants,excessive_hair_growth_on_face,unusual_production_of_breast_milk_in_women_and...,pancreatic_inflammation,increased_androgen_levels,decreased_libido,headache,dizziness,blurred_vision,cataract,ring_scotoma,double_vision,lacrimation_flow_of_tears,hypotension_low_blood_pressure,enlarged_heart,cardiac_failure,arrhythmia_irregular_heartbeats,breathlessness,pulmonary_hypertension_high_blood_pressure,increased_aspartate_aminotransferase,increased_alkaline_phosphatase_level_in_blood,"musculoskeletal_bone,_muscle_or_joint_pain",azotemia_increased_nitrogen_containing_compoun...,decreased_creatinine_clearance,nephritic_syndrome,voice_change,abnormal_faces_in_children,managing_hypoglycemia_low_blood_sugar,missing,missing,missing,missing,thiadiazines_derivative,no,anti_diabetic,missing,1478.0,false,jolly_healthcare,allopathy,strip_of_10_capsules,diazoxide_25mg,missing
42801,cytoflu_500mg_tablet,cytorx_500mg_tablet,fcfung_500_tablet,missing,missing,missing,nausea,vomiting,diarrhea,skin_rash,missing,missing,missing,missing,missing,missing,missing,missing,missing,missing,missing,missing,missing,missing,missing,missing,missing,missing,missing,missing,missing,missing,missing,missing,missing,missing,missing,missing,missing,missing,missing,missing,missing,missing,missing,missing,missing,missing,_severe_fungal_infections,missing,missing,missing,missing,nucleoside_analog_{antimetabolite},no,anti_infectives,fluorinated_pyrimidine_antifungal,13500.0,false,jolly_healthcare,allopathy,bottle_of_100_tablets,flucytosine_500mg,missing
43203,cabaza_tablet,rb_flex_400mg_tablet,kinetal_400mg_tablet,flowpent_400mg_tablet,perital_400mg_tablet,flexital_400mg_tablet,bloating,diarrhea,"flushing_sense_of_warmth_in_the_face,_ears,_ne...",headache,heartburn,lightheadedness,nausea,stomach_discomfort,vomiting,weakness,missing,missing,missing,missing,missing,missing,missing,missing,missing,missing,missing,missing,missing,missing,missing,missing,missing,missing,missing,missing,missing,missing,missing,missing,missing,missing,missing,missing,missing,missing,missing,missing,_peripheral_vascular_disease,_intermittent_claudication,missing,missing,missing,methylxanthine_derivative,no,cardiac,rheologic_modifier,112.0,false,jolly_healthcare,allopathy,strip_of_10_tablets,pentoxifylline_400mg,missing
49259,cabaza_tablet_er,pentoxia_400_er_tablet,missing,missing,missing,missing,bloating,diarrhea,"flushing_sense_of_warmth_in_the_face,_ears,_ne...",headache,heartburn,lightheadedness,nausea,stomach_discomfort,vomiting,weakness,missing,missing,missing,missing,missing,missing,missing,missing,missing,missing,missing,missing,missing,missing,missing,missing,missing,missing,missing,missing,missing,missing,missing,missing,missing,missing,missing,missing,missing,missing,missing,missing,_peripheral_vascular_disease,_intermittent_claudication,missing,missing,missing,methylxanthine_derivative,no,cardiac,rheologic_modifier,112.0,false,jolly_healthcare,allopathy,strip_of_10_tablet_er,pentoxifylline_400mg,missing
55438,casjol_50_injection,capsain_50mg_injection,hospicasp_50mg_injection,casogyn_50mg_injection,casponova_50mg_injection,casporan_50mg_injection,chills,decreased_potassium_level_in_blood,diarrhea,fever,increased_alkaline_phosphatase_level_in_blood,increased_liver_enzymes,rash,missing,missing,missing,missing,missing,missing,missing,missing,missing,missing,missing,missing,missing,missing,missing,missing,missing,missing,missing,missing,missing,missing,missing,missing,missing,missing,missing,missing,missing,missing,missing,missing,missing,missing,missing,_severe_fungal_infections,missing,missing,missing,missing,echinocandins,no,others,fungal_cell_wall_synthesis_inhibitor_echiocandins,8900.0,false,jolly_healthcare,allopathy,vial_of_1_injection,caspofungin_50mg,missing
116145,huelin_injection,missing,missing,missing,missing,missing,rash,allergic_reaction,"injection_site_reactions_pain,_swelling,_redness",missing,missing,missing,missing,missing,missing,missing,missing,missing,missing,missing,missing,missing,missing,missing,missing,missing,missing,missing,missing,missing,missing,missing,missing,missing,missing,missing,missing,missing,missing,missing,missing,missing,missing,missing,missing,missing,missing,missing,treatment_of_bacterial_infections,treatment_of_syphilis,prevention_of_rheumatic_fever,missing,missing,penicillins,no,anti_infectives,cell_wall_active_agent___narrow_spectrum_penic...,80.0,false,jolly_healthcare,allopathy,vial_of_1_injection,benzathine_penicillin_g_24lac_units,missing
125979,jolltrim_ds_tablet,cortina_ds_800mg_160mg_tablet,colizole_ds_800mg_160mg_tablet,tabrol_ds_tablet,trisulfose_ds_800mg_160mg_tablet,sepmax_ds_tablet,nausea,vomiting,skin_rash,allergic_reaction,missing,missing,missing,missing,missing,missing,missing,missing,missing,missing,missing,missing,missing,missing,missing,missing,missing,missing,missing,missing,missing,missing,missing,missing,missing,missing,missing,missing,missing,missing,missing,missing,missing,missing,missing,missing,missing,missing,treatment_of_bacterial_infections,missing,missing,missing,missing,missing,no,anti_infectives,missing,38.5,false,jolly_healthcare,allopathy,strip_of_10_tablets,sulfamethoxazole_800mg_,_trimethoprim_160mg
125992,jolavi_tablet,midgeo_tablet,actiful_2.5mg_tablet,midotab_2.5_tablet,midrex_2.5mg_tablet,aladrine_2.5mg_tablet,headache,nausea,rash,difficulty_in_urination,missing,missing,missing,missing,missing,missing,missing,missing,missing,missing,missing,missing,missing,missing,missing,missing,missing,missing,missing,missing,missing,missing,missing,missing,missing,missing,missing,missing,missing,missing,missing,missing,missing,missing,missing,missing,missing,missing,_low_blood_pressure,missing,missing,missing,missing,ethanolamine_derivative,no,cardiac,alpha_1_adrenoreceptor_agonists,199.98,false,jolly_healthcare,allopathy,strip_of_10_tablets,midodrine_2.5mg,missing
126069,jolltrin_capsule,missing,missing,missing,missing,missing,systemic_lupus_erythematosus,iron_deficiency,dystonia_involuntary_muscle_contractions,muscle_spasm,myasthenia_gravis,missing,missing,missing,missing,missing,missing,missing,missing,missing,missing,missing,missing,missing,missing,missing,missing,missing,missing,missing,missing,missing,missing,missing,missing,missing,missing,missing,missing,missing,missing,missing,missing,missing,missing,missing,missing,missing,_wilson's_disease,missing,missing,missing,missing,ethylenediamine_derivative,no,gastro_intestinal,missing,19500.0,false,jolly_healthcare,allopathy,bottle_of_100_capsules,trientine_hydrochloride_250mg,missing
126161,jollimex_150_capsule,welhart_150mg_capsule,mexohar_150mg_capsule,missing,missing,missing,nausea,vomiting,dizziness,chest_pain,tremors,breathlessness,palpitations,heartburn,lightheadedness,missing,missing,missing,missing,missing,missing,missing,missing,missing,missing,missing,missing,missing,missing,missing,missing,missing,missing,missing,missing,missing,missing,missing,missing,missing,missing,missing,missing,missing,missing,missing,missing,missing,_arrhythmia,missing,missing,missing,missing,phenol_ethers,no,cardiac,class_i_agents__anti_arrhythmic,729.0,false,jolly_healthcare,allopathy,strip_of_10_capsules,mexiletine_150mg,missing
126165,jolclo_injection,missing,missing,missing,missing,missing,rash,"injection_site_reactions_pain,_swelling,_redness",allergic_reaction,missing,missing,missing,missing,missing,missing,missing,missing,missing,missing,missing,missing,missing,missing,missing,missing,missing,missing,missing,missing,missing,missing,missing,missing,missing,missing,missing,missing,missing,missing,missing,missing,missing,missing,missing,missing,missing,missing,missing,_bacterial_infections,missing,missing,missing,missing,antistaphylococcal_penicillin,no,anti_infectives,cell_wall_active_agent__penicillinase_resistan...,110.0,false,jolly_healthcare,allopathy,vial_of_1_injection,cloxacillin_1000mg,missing
126203,jollpen_injection,missing,missing,missing,missing,missing,rash,allergic_reaction,"injection_site_reactions_pain,_swelling,_redness",missing,missing,missing,missing,missing,missing,missing,missing,missing,missing,missing,missing,missing,missing,missing,missing,missing,missing,missing,missing,missing,missing,missing,missing,missing,missing,missing,missing,missing,missing,missing,missing,missing,missing,missing,missing,missing,missing,missing,treatment_of_bacterial_infections,treatment_of_syphilis,prevention_of_rheumatic_fever,missing,missing,penicillins,no,anti_infectives,cell_wall_active_agent___narrow_spectrum_penic...,77.0,false,jolly_healthcare,allopathy,vial_of_1_injection,penicillin_g_5lac_units,missing
126278,jolvig_oral_solution,missing,missing,missing,missing,missing,blurred_vision,double_vision,tremors,weight_gain,headache,sleepiness,diarrhea,nausea,nasopharyngitis_inflammation_of_the_throat_and...,peripheral_edema,missing,missing,missing,missing,missing,missing,missing,missing,missing,missing,missing,missing,missing,missing,missing,missing,missing,missing,missing,missing,missing,missing,missing,missing,missing,missing,missing,missing,missing,missing,missing,missing,_epilepsy_seizures,_infantile_spasms,missing,missing,missing,gaba_derivative,no,neuro_cns,gaba_transaminase_inhibitor_aed,69.95,false,jolly_healthcare,allopathy,packet_of_1_sachet,vigabatrin_500mg,missing
126313,jollimex_50_capsule,welhart_50mg_capsule,mexohar_50mg_capsule,missing,missing,missing,nausea,vomiting,dizziness,chest_pain,tremors,breathlessness,palpitations,heartburn,lightheadedness,missing,missing,missing,missing,missing,missing,missing,missing,missing,missing,missing,missing,missing,missing,missing,missing,missing,missing,missing,missing,missing,missing,missing,missing,missing,missing,missing,missing,missing,missing,missing,missing,missing,_arrhythmia,missing,missing,missing,missing,phenol_ethers,no,cardiac,class_i_agents__anti_arrhythmic,249.0,false,jolly_healthcare,allopathy,strip_of_10_capsules,mexiletine_50mg,missing
126333,jolltrim_oral_suspension,centri_oral_suspension,m_prim_ds_oral_suspension,septran_paediatric_oral_suspension,septran_paediatric_oral_suspension,missing,nausea,vomiting,skin_rash,allergic_reaction,missing,missing,missing,missing,missing,missing,missing,missing,missing,missing,missing,missing,missing,missing,missing,missing,missing,missing,missing,missing,missing,missing,missing,missing,missing,missing,missing,missing,missing,missing,missing,missing,missing,missing,missing,missing,missing,missing,treatment_of_bacterial_infections,missing,missing,missing,missing,missing,no,anti_infectives,missing,31.25,false,jolly_healthcare,allopathy,bottle_of_50_ml_oral_suspension,sulfamethoxazole_200mg_5ml_,_trimethoprim_40mg_5ml
126439,jolltrim_400mg_80mg_injection,klotrim_injection,missing,missing,missing,missing,nausea,vomiting,weight_loss,rash,hives,missing,missing,missing,missing,missing,missing,missing,missing,missing,missing,missing,missing,missing,missing,missing,missing,missing,missing,missing,missing,missing,missing,missing,missing,missing,missing,missing,missing,missing,missing,missing,missing,missing,missing,missing,missing,missing,treatment_of_bacterial_infections,missing,missing,missing,missing,missing,no,anti_infectives,missing,200.0,false,jolly_healthcare,allopathy,vial_of_5_ml_injection,sulfamethoxazole_400mg_,_trimethoprim_80mg
126615,jolclo_500mg_injection,bioclox_500mg_injection,klox_500mg_injection,neoclox_500mg_injection,mediclox_500mg_injection,missing,rash,"injection_site_reactions_pain,_swelling,_redness",allergic_reaction,missing,missing,missing,missing,missing,missing,missing,missing,missing,missing,missing,missing,missing,missing,missing,missing,missing,missing,missing,missing,missing,missing,missing,missing,missing,missing,missing,missing,missing,missing,missing,missing,missing,missing,missing,missing,missing,missing,missing,_bacterial_infections,missing,missing,missing,missing,antistaphylococcal_penicillin,no,anti_infectives,cell_wall_active_agent__penicillinase_resistan...,60.0,false,jolly_healthcare,allopathy,vial_of_1_injection,cloxacillin_500mg,missing
151202,mycoflu_injection,neotericin_50mg_injection,amfocan_50mg_injection,amtericin_50mg_injection,fungitericin_injection,ambiship_injection,"injection_site_reactions_pain,_swelling,_redness",nausea,vomiting,chills,headache,anemia_low_number_of_red_blood_cells,decreased_potassium_level_in_blood,abnormal_liver_function_tests,decreased_magnesium_level_in_blood,diarrhea,decreased_appetite,hypotension_low_blood_pressure,skin_rash,nephrocalcinosis,increased_creatinine_level_in_blood,abnormal_renal_function_tests,renal_tubular_acidosis,missing,missing,missing,missing,missing,missing,missing,missing,missing,missing,missing,missing,missing,missing,missing,missing,missing,missing,missing,missing,missing,missing,missing,missing,missing,_severe_fungal_infections,_kala_azar,missing,missing,missing,aminoglycosides_{polyenes},no,anti_infectives,fungal_cell_membrane_active_agent,326.0,false,jolly_healthcare,allopathy,vial_of_1_injection,amphotericin_b_50mg,missing
153290,mycoflu_e_injection,neotericin_50mg_injection,amfocan_50mg_injection,amtericin_50mg_injection,fungitericin_injection,mycoflu_injection,"injection_site_reactions_pain,_swelling,_redness",nausea,vomiting,chills,headache,anemia_low_number_of_red_blood_cells,decreased_potassium_level_in_blood,abnormal_liver_function_tests,decreased_magnesium_level_in_blood,diarrhea,decreased_appetite,hypotension_low_blood_pressure,skin_rash,nephrocalcinosis,increased_creatinine_level_in_blood,abnormal_renal_function_tests,renal_tubular_acidosis,missing,missing,missing,missing,missing,missing,missing,missing,missing,missing,missing,missing,missing,missing,missing,missing,missing,missing,missing,missing,missing,missing,missing,missing,missing,_severe_fungal_infections,_kala_azar,missing,missing,missing,aminoglycosides_{polyenes},no,anti_infectives,fungal_cell_membrane_active_agent,4500.0,false,jolly_healthcare,allopathy,vial_of_10_ml_injection,amphotericin_b_50mg,missing
156584,mycoflu_l_injection,sporotar_50mg_injection,abhope_50mg_injection,amphogard_50mg_injection,lambin_injection,fungsome_50mg_injection,decreased_potassium_level_in_blood,nausea,vomiting,chills,fever,missing,missing,missing,missing,missing,missing,missing,missing,missing,missing,missing,missing,missing,missing,missing,missing,missing,missing,missing,missing,missing,missing,missing,missing,missing,missing,missing,missing,missing,missing,missing,missing,missing,missing,missing,missing,missing,treatment_of_severe_fungal_infections,treatment_of_leishmaniasis.,missing,missing,missing,aminoglycosides_{polyenes},no,anti_infectives,fungal_cell_membrane_active_agent,7484.0,false,jolly_healthcare,allopathy,vial_of_1_injection,liposomal_amphotericin_b_50mg,missing
168720,nostof_500mg_injection,reflin_500mg_injection,alcizon_500mg_injection,sefazol_500mg_injection,azolin_500mg_injection,cezolin_500mg_injection,rash,"injection_site_reactions_pain,_swelling,_redness",allergic_reaction,nausea,indigestion,diarrhea,missing,missing,missing,missing,missing,missing,missing,missing,missing,missing,missing,missing,missing,missing,missing,missing,missing,missing,missing,missing,missing,missing,missing,missing,missing,missing,missing,missing,missing,missing,missing,missing,missing,missing,missing,missing,_bacterial_infections,missing,missing,missing,missing,narrow__specttrum_{first_generation_cephalospo...,no,anti_infectives,cephalosporins:_1st_generation,39.95,false,jolly_healthcare,allopathy,vial_of_1_injection,cefazolin_500mg,missing
169394,nostof_1gm_injection,alcizon_1gm_injection,negcin_1gm_injection,reflin_1gm_injection,cezolin_1gm_injection,missing,rash,"injection_site_reactions_pain,_swelling,_redness",allergic_reaction,nausea,indigestion,diarrhea,missing,missing,missing,missing,missing,missing,missing,missing,missing,missing,missing,missing,missing,missing,missing,missing,missing,missing,missing,missing,missing,missing,missing,missing,missing,missing,missing,missing,missing,missing,missing,missing,missing,missing,missing,missing,_bacterial_infections,missing,missing,missing,missing,narrow__specttrum_{first_generation_cephalospo...,no,anti_infectives,cephalosporins:_1st_generation,25.81,false,jolly_healthcare,allopathy,vial_of_1_injection,cefazolin_1gm,missing
173079,nostof_250mg_injection,reflin_250mg_injection,alcizon_250mg_injection,cezolin_250mg_injection,missing,missing,rash,"injection_site_reactions_pain,_swelling,_redness",allergic_reaction,nausea,indigestion,diarrhea,missing,missing,missing,missing,missing,missing,missing,missing,missing,missing,missing,missing,missing,missing,missing,missing,missing,missing,missing,missing,missing,missing,missing,missing,missing,missing,missing,missing,missing,missing,missing,missing,missing,missing,missing,missing,_bacterial_infections,missing,missing,missing,missing,narrow__specttrum_{first_generation_cephalospo...,no,anti_infectives,cephalosporins:_1st_generation,27.5,false,jolly_healthcare,allopathy,vial_of_1_injection,cefazolin_250mg,missing

Is diazoxide 25mg, which is a thiadiazines derivative causing a lot of side effects?